language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt install mesa-utils mesa-common-dev freeglut3-dev libglew-dev libglm-dev libsoil-dev -y
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
