language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo apt install mesa-utils mesa-common-dev freeglut3-dev libglew-dev libglm-dev libsoil-dev -y
  - sudo apt remove cmake
  - sudo wget -O /tmp/cmake.sh https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh
  - sudo ./tmp/cmake.sh
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
