language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update
  - sudo apt install mesa-utils mesa-common-dev freeglut3-dev libglew-dev libglm-dev libsoil-dev -y
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
